version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_USER=synapse
      - POSTGRES_DB=synapse

  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - synapse-data:/data
      - ./homeserver.yaml:/data/homeserver.yaml:ro
    environment:
      - SYNAPSE_SERVER_NAME=your-domain.com
      - SYNAPSE_REPORT_STATS=no
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_USER=synapse
      - POSTGRES_DB=synapse
      - POSTGRES_HOST=db
    ports:
      - "8008:8008"
      - "8448:8448"

  element:
    build: .
    container_name: element
    restart: unless-stopped
    ports:
      - "30000:80"
    environment:
      - NODE_ENV=production

volumes:
  postgres-data:
  synapse-data: 